// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: stock.
// - Entity ID: 102019ac49f110076e3a5fb5f419be34c27.
// - Entity Version: 102019b11cfa3a378f586276c85196669dd.
// - Task ID: 693bdaebf3e1deef7a9703e2.
// - Task Root ID: 69281530eba4976d6c38ab7a.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for StockModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface StockModel {
  id: string;
  symbol: string;
  company_name: string;
  current_price: number;
  previous_close: number;
  day_high: number;
  day_low: number;
  week_52_high: number;
  week_52_low: number;
  market_cap: string;
  pe_ratio?: number | null;
  volume: string;
  description?: string | null;
  sector?: string | null;
  is_featured: boolean;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for Stock entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class StockORM {
  private static instance: StockORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac49f110076e3a5fb5f419be34c27';
    this.entityName = 'stock';
    this.entityVersion = '102019b11cfa3a378f586276c85196669dd';
    this.taskId = '693bdaebf3e1deef7a9703e2';
    this.taskRootId = '69281530eba4976d6c38ab7a';
  }

  /**
   * Get singleton instance of StockORM
   */
  public static getInstance(): StockORM {
    if (!StockORM.instance) {
      StockORM.instance = new StockORM();
    }
    
    return StockORM.instance;
  }

  /**
   * Get all Stock records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllStock(): Promise<StockModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Stock record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertStock(data: StockModel[]): Promise<StockModel[]> {
    const structured = data.map((item) => CreateData(StockModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Stock records
   */
  async purgeAllStock(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Stock records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listStock(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[StockModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get stock by Id index
   * This function gets data by index.
   */
  async getStockById(
    id: string,
  ): Promise<StockModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) stock by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setStockById(
    id: string,
    data: StockModel
  ): Promise<StockModel[]> {
    const index = createIndexId(
      id
    );

    const values = StockModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete stock by Id index
   */
  async deleteStockById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get stock by Symbol index
   * This function gets data by index.
   */
  async getStockBySymbol(
    symbol: string,
  ): Promise<StockModel[]> {
    const index = createIndexSymbol(
      symbol
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) stock by Symbol index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setStockBySymbol(
    symbol: string,
    data: StockModel
  ): Promise<StockModel[]> {
    const index = createIndexSymbol(
      symbol
    );

    const values = StockModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete stock by Symbol index
   */
  async deleteStockBySymbol(
    symbol: string
  ): Promise<void> {
    const index = createIndexSymbol(
      symbol
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get stock by Sector index
   * This function gets data by index.
   */
  async getStockBySector(
    sector: string,
  ): Promise<StockModel[]> {
    const index = createIndexSector(
      sector
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) stock by Sector index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setStockBySector(
    sector: string,
    data: StockModel
  ): Promise<StockModel[]> {
    const index = createIndexSector(
      sector
    );

    const values = StockModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete stock by Sector index
   */
  async deleteStockBySector(
    sector: string
  ): Promise<void> {
    const index = createIndexSector(
      sector
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get stock by IsFeatured index
   * This function gets data by index.
   */
  async getStockByIsFeatured(
    is_featured: boolean,
  ): Promise<StockModel[]> {
    const index = createIndexIsFeatured(
      is_featured
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) stock by IsFeatured index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setStockByIsFeatured(
    is_featured: boolean,
    data: StockModel
  ): Promise<StockModel[]> {
    const index = createIndexIsFeatured(
      is_featured
    );

    const values = StockModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete stock by IsFeatured index
   */
  async deleteStockByIsFeatured(
    is_featured: boolean
  ): Promise<void> {
    const index = createIndexIsFeatured(
      is_featured
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get stock by DataCreator index
   * This function gets data by index.
   */
  async getStockByDataCreator(
    data_creator: string,
  ): Promise<StockModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) stock by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setStockByDataCreator(
    data_creator: string,
    data: StockModel
  ): Promise<StockModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = StockModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete stock by DataCreator index
   */
  async deleteStockByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get stock by DataUpdater index
   * This function gets data by index.
   */
  async getStockByDataUpdater(
    data_updater: string,
  ): Promise<StockModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) stock by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setStockByDataUpdater(
    data_updater: string,
    data: StockModel
  ): Promise<StockModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = StockModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete stock by DataUpdater index
   */
  async deleteStockByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to StockModel data array
   */
  private resultToData(values: Data[]): StockModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return StockModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as StockModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized StockModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is StockModel => item !== null);
  }
}

/**
 * Convert StockModel data to Value array
 */
function StockModelToValues(data: StockModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'symbol', type: DataType.string, defaultValue: '' },
    { key: 'company_name', type: DataType.string, defaultValue: '' },
    { key: 'current_price', type: DataType.number, defaultValue: 0 },
    { key: 'previous_close', type: DataType.number, defaultValue: 0 },
    { key: 'day_high', type: DataType.number, defaultValue: 0 },
    { key: 'day_low', type: DataType.number, defaultValue: 0 },
    { key: 'week_52_high', type: DataType.number, defaultValue: 0 },
    { key: 'week_52_low', type: DataType.number, defaultValue: 0 },
    { key: 'market_cap', type: DataType.string, defaultValue: '' },
    { key: 'pe_ratio', type: DataType.number, defaultValue: null },
    { key: 'volume', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'sector', type: DataType.string, defaultValue: null },
    { key: 'is_featured', type: DataType.boolean, defaultValue: false },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof StockModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to StockModel data
 */
function StockModelFromValues(values: Value[]): StockModel {
  const data: Partial<StockModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'symbol':
        data.symbol = ParseValue(value, DataType.string) as string;
        break;
      case 'company_name':
        data.company_name = ParseValue(value, DataType.string) as string;
        break;
      case 'current_price':
        data.current_price = ParseValue(value, DataType.number) as number;
        break;
      case 'previous_close':
        data.previous_close = ParseValue(value, DataType.number) as number;
        break;
      case 'day_high':
        data.day_high = ParseValue(value, DataType.number) as number;
        break;
      case 'day_low':
        data.day_low = ParseValue(value, DataType.number) as number;
        break;
      case 'week_52_high':
        data.week_52_high = ParseValue(value, DataType.number) as number;
        break;
      case 'week_52_low':
        data.week_52_low = ParseValue(value, DataType.number) as number;
        break;
      case 'market_cap':
        data.market_cap = ParseValue(value, DataType.string) as string;
        break;
      case 'pe_ratio':
        data.pe_ratio = ParseValue(value, DataType.number) as number | null;
        break;
      case 'volume':
        data.volume = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'sector':
        data.sector = ParseValue(value, DataType.string) as string | null;
        break;
      case 'is_featured':
        data.is_featured = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as StockModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for Symbol fields
 */
function createIndexSymbol(
  symbol: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, symbol, 'symbol'),
  ];

  return {
    fields: ['symbol'],
    values
  };
}
/**
 * Create index for Sector fields
 */
function createIndexSector(
  sector: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, sector, 'sector'),
  ];

  return {
    fields: ['sector'],
    values
  };
}
/**
 * Create index for IsFeatured fields
 */
function createIndexIsFeatured(
  is_featured: boolean
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_featured, 'is_featured'),
  ];

  return {
    fields: ['is_featured'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default StockORM;