// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: exclusive_content.
// - Entity ID: 102019ac49f11007c2a9cd49766107d8a9b.
// - Entity Version: 102019b11cfa3a378f586276c85196669dd.
// - Task ID: 693bdaebf3e1deef7a9703e2.
// - Task Root ID: 69281530eba4976d6c38ab7a.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ExclusiveContentContentType
 */
export enum ExclusiveContentContentType {
  Unspecified = 0,
  Video = 1,
  Photo = 2,
  Article = 3,
  Announcement = 4,
}



/**
 * Interface for ExclusiveContentModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ExclusiveContentModel {
  id: string;
  title: string;
  description?: string | null;
  content_type: ExclusiveContentContentType;
  content_url: string;
  thumbnail_url?: string | null;
  min_shares_required: number;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for ExclusiveContent entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ExclusiveContentORM {
  private static instance: ExclusiveContentORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac49f11007c2a9cd49766107d8a9b';
    this.entityName = 'exclusive_content';
    this.entityVersion = '102019b11cfa3a378f586276c85196669dd';
    this.taskId = '693bdaebf3e1deef7a9703e2';
    this.taskRootId = '69281530eba4976d6c38ab7a';
  }

  /**
   * Get singleton instance of ExclusiveContentORM
   */
  public static getInstance(): ExclusiveContentORM {
    if (!ExclusiveContentORM.instance) {
      ExclusiveContentORM.instance = new ExclusiveContentORM();
    }
    
    return ExclusiveContentORM.instance;
  }

  /**
   * Get all ExclusiveContent records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllExclusiveContent(): Promise<ExclusiveContentModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ExclusiveContent record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertExclusiveContent(data: ExclusiveContentModel[]): Promise<ExclusiveContentModel[]> {
    const structured = data.map((item) => CreateData(ExclusiveContentModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ExclusiveContent records
   */
  async purgeAllExclusiveContent(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ExclusiveContent records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listExclusiveContent(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ExclusiveContentModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get exclusive_content by Id index
   * This function gets data by index.
   */
  async getExclusiveContentById(
    id: string,
  ): Promise<ExclusiveContentModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exclusive_content by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExclusiveContentById(
    id: string,
    data: ExclusiveContentModel
  ): Promise<ExclusiveContentModel[]> {
    const index = createIndexId(
      id
    );

    const values = ExclusiveContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exclusive_content by Id index
   */
  async deleteExclusiveContentById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get exclusive_content by ContentType index
   * This function gets data by index.
   */
  async getExclusiveContentByContentType(
    content_type: ExclusiveContentContentType,
  ): Promise<ExclusiveContentModel[]> {
    const index = createIndexContentType(
      content_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exclusive_content by ContentType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExclusiveContentByContentType(
    content_type: ExclusiveContentContentType,
    data: ExclusiveContentModel
  ): Promise<ExclusiveContentModel[]> {
    const index = createIndexContentType(
      content_type
    );

    const values = ExclusiveContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exclusive_content by ContentType index
   */
  async deleteExclusiveContentByContentType(
    content_type: ExclusiveContentContentType
  ): Promise<void> {
    const index = createIndexContentType(
      content_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get exclusive_content by DataCreator index
   * This function gets data by index.
   */
  async getExclusiveContentByDataCreator(
    data_creator: string,
  ): Promise<ExclusiveContentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exclusive_content by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExclusiveContentByDataCreator(
    data_creator: string,
    data: ExclusiveContentModel
  ): Promise<ExclusiveContentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ExclusiveContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exclusive_content by DataCreator index
   */
  async deleteExclusiveContentByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get exclusive_content by DataUpdater index
   * This function gets data by index.
   */
  async getExclusiveContentByDataUpdater(
    data_updater: string,
  ): Promise<ExclusiveContentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exclusive_content by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExclusiveContentByDataUpdater(
    data_updater: string,
    data: ExclusiveContentModel
  ): Promise<ExclusiveContentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ExclusiveContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exclusive_content by DataUpdater index
   */
  async deleteExclusiveContentByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ExclusiveContentModel data array
   */
  private resultToData(values: Data[]): ExclusiveContentModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ExclusiveContentModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ExclusiveContentModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ExclusiveContentModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ExclusiveContentModel => item !== null);
  }
}

/**
 * Convert ExclusiveContentModel data to Value array
 */
function ExclusiveContentModelToValues(data: ExclusiveContentModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'content_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'content_url', type: DataType.string, defaultValue: '' },
    { key: 'thumbnail_url', type: DataType.string, defaultValue: null },
    { key: 'min_shares_required', type: DataType.number, defaultValue: 0 },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ExclusiveContentModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ExclusiveContentModel data
 */
function ExclusiveContentModelFromValues(values: Value[]): ExclusiveContentModel {
  const data: Partial<ExclusiveContentModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'content_type':
        data.content_type = ParseValue(value, DataType.enumeration) as ExclusiveContentContentType;
        break;
      case 'content_url':
        data.content_url = ParseValue(value, DataType.string) as string;
        break;
      case 'thumbnail_url':
        data.thumbnail_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'min_shares_required':
        data.min_shares_required = ParseValue(value, DataType.number) as number;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as ExclusiveContentModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for ContentType fields
 */
function createIndexContentType(
  content_type: ExclusiveContentContentType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, content_type, 'content_type'),
  ];

  return {
    fields: ['content_type'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ExclusiveContentORM;