// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: notification.
// - Entity ID: 102019ac49f11007af69b45c1df926cc23d.
// - Entity Version: 102019b11cfa3a378f586276c85196669dd.
// - Task ID: 693bdaebf3e1deef7a9703e2.
// - Task Root ID: 69281530eba4976d6c38ab7a.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for NotificationType
 */
export enum NotificationType {
  Unspecified = 0,
  OrderExecuted = 1,
  PriceAlert = 2,
  Content = 3,
  Announcement = 4,
}



/**
 * Interface for NotificationModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface NotificationModel {
  id: string;
  user_id: string;
  type: NotificationType;
  title: string;
  message: string;
  is_read: boolean;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for Notification entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class NotificationORM {
  private static instance: NotificationORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac49f11007af69b45c1df926cc23d';
    this.entityName = 'notification';
    this.entityVersion = '102019b11cfa3a378f586276c85196669dd';
    this.taskId = '693bdaebf3e1deef7a9703e2';
    this.taskRootId = '69281530eba4976d6c38ab7a';
  }

  /**
   * Get singleton instance of NotificationORM
   */
  public static getInstance(): NotificationORM {
    if (!NotificationORM.instance) {
      NotificationORM.instance = new NotificationORM();
    }
    
    return NotificationORM.instance;
  }

  /**
   * Get all Notification records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllNotification(): Promise<NotificationModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Notification record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertNotification(data: NotificationModel[]): Promise<NotificationModel[]> {
    const structured = data.map((item) => CreateData(NotificationModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Notification records
   */
  async purgeAllNotification(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Notification records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listNotification(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[NotificationModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get notification by Id index
   * This function gets data by index.
   */
  async getNotificationById(
    id: string,
  ): Promise<NotificationModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) notification by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNotificationById(
    id: string,
    data: NotificationModel
  ): Promise<NotificationModel[]> {
    const index = createIndexId(
      id
    );

    const values = NotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete notification by Id index
   */
  async deleteNotificationById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get notification by CreateTimeIsReadUserId index
   * This function gets data by index.
   */
  async getNotificationByCreateTimeIsReadUserId(
    create_time: string,
    is_read: boolean,
    user_id: string,
  ): Promise<NotificationModel[]> {
    const index = createIndexCreateTimeIsReadUserId(
      create_time,
      is_read,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) notification by CreateTimeIsReadUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNotificationByCreateTimeIsReadUserId(
    create_time: string,
    is_read: boolean,
    user_id: string,
    data: NotificationModel
  ): Promise<NotificationModel[]> {
    const index = createIndexCreateTimeIsReadUserId(
      create_time,
      is_read,
      user_id
    );

    const values = NotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete notification by CreateTimeIsReadUserId index
   */
  async deleteNotificationByCreateTimeIsReadUserId(
    create_time: string,
    is_read: boolean,
    user_id: string
  ): Promise<void> {
    const index = createIndexCreateTimeIsReadUserId(
      create_time,
      is_read,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get notification by DataCreator index
   * This function gets data by index.
   */
  async getNotificationByDataCreator(
    data_creator: string,
  ): Promise<NotificationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) notification by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNotificationByDataCreator(
    data_creator: string,
    data: NotificationModel
  ): Promise<NotificationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = NotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete notification by DataCreator index
   */
  async deleteNotificationByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get notification by DataUpdater index
   * This function gets data by index.
   */
  async getNotificationByDataUpdater(
    data_updater: string,
  ): Promise<NotificationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) notification by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNotificationByDataUpdater(
    data_updater: string,
    data: NotificationModel
  ): Promise<NotificationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = NotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete notification by DataUpdater index
   */
  async deleteNotificationByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to NotificationModel data array
   */
  private resultToData(values: Data[]): NotificationModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return NotificationModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as NotificationModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized NotificationModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is NotificationModel => item !== null);
  }
}

/**
 * Convert NotificationModel data to Value array
 */
function NotificationModelToValues(data: NotificationModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'message', type: DataType.string, defaultValue: '' },
    { key: 'is_read', type: DataType.boolean, defaultValue: false },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof NotificationModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to NotificationModel data
 */
function NotificationModelFromValues(values: Value[]): NotificationModel {
  const data: Partial<NotificationModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'type':
        data.type = ParseValue(value, DataType.enumeration) as NotificationType;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'message':
        data.message = ParseValue(value, DataType.string) as string;
        break;
      case 'is_read':
        data.is_read = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as NotificationModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for CreateTimeIsReadUserId fields
 */
function createIndexCreateTimeIsReadUserId(
  create_time: string,
  is_read: boolean,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
    CreateValue(DataType.boolean, is_read, 'is_read'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['create_time', 'is_read', 'user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default NotificationORM;