// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: portfolio.
// - Entity ID: 102019ac49f110071389b9d530f87c99f80.
// - Entity Version: 102019b11cfa3a378f586276c85196669dd.
// - Task ID: 693bdaebf3e1deef7a9703e2.
// - Task Root ID: 69281530eba4976d6c38ab7a.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for PortfolioModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface PortfolioModel {
  id: string;
  user_id: string;
  stock_id: string;
  shares: number;
  average_cost: number;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for Portfolio entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class PortfolioORM {
  private static instance: PortfolioORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac49f110071389b9d530f87c99f80';
    this.entityName = 'portfolio';
    this.entityVersion = '102019b11cfa3a378f586276c85196669dd';
    this.taskId = '693bdaebf3e1deef7a9703e2';
    this.taskRootId = '69281530eba4976d6c38ab7a';
  }

  /**
   * Get singleton instance of PortfolioORM
   */
  public static getInstance(): PortfolioORM {
    if (!PortfolioORM.instance) {
      PortfolioORM.instance = new PortfolioORM();
    }
    
    return PortfolioORM.instance;
  }

  /**
   * Get all Portfolio records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllPortfolio(): Promise<PortfolioModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Portfolio record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertPortfolio(data: PortfolioModel[]): Promise<PortfolioModel[]> {
    const structured = data.map((item) => CreateData(PortfolioModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Portfolio records
   */
  async purgeAllPortfolio(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Portfolio records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listPortfolio(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[PortfolioModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get portfolio by Id index
   * This function gets data by index.
   */
  async getPortfolioById(
    id: string,
  ): Promise<PortfolioModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) portfolio by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPortfolioById(
    id: string,
    data: PortfolioModel
  ): Promise<PortfolioModel[]> {
    const index = createIndexId(
      id
    );

    const values = PortfolioModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete portfolio by Id index
   */
  async deletePortfolioById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get portfolio by StockIdUserId index
   * This function gets data by index.
   */
  async getPortfolioByStockIdUserId(
    stock_id: string,
    user_id: string,
  ): Promise<PortfolioModel[]> {
    const index = createIndexStockIdUserId(
      stock_id,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) portfolio by StockIdUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPortfolioByStockIdUserId(
    stock_id: string,
    user_id: string,
    data: PortfolioModel
  ): Promise<PortfolioModel[]> {
    const index = createIndexStockIdUserId(
      stock_id,
      user_id
    );

    const values = PortfolioModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete portfolio by StockIdUserId index
   */
  async deletePortfolioByStockIdUserId(
    stock_id: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexStockIdUserId(
      stock_id,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get portfolio by DataCreator index
   * This function gets data by index.
   */
  async getPortfolioByDataCreator(
    data_creator: string,
  ): Promise<PortfolioModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) portfolio by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPortfolioByDataCreator(
    data_creator: string,
    data: PortfolioModel
  ): Promise<PortfolioModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = PortfolioModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete portfolio by DataCreator index
   */
  async deletePortfolioByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get portfolio by DataUpdater index
   * This function gets data by index.
   */
  async getPortfolioByDataUpdater(
    data_updater: string,
  ): Promise<PortfolioModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) portfolio by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPortfolioByDataUpdater(
    data_updater: string,
    data: PortfolioModel
  ): Promise<PortfolioModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = PortfolioModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete portfolio by DataUpdater index
   */
  async deletePortfolioByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to PortfolioModel data array
   */
  private resultToData(values: Data[]): PortfolioModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return PortfolioModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as PortfolioModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized PortfolioModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is PortfolioModel => item !== null);
  }
}

/**
 * Convert PortfolioModel data to Value array
 */
function PortfolioModelToValues(data: PortfolioModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'stock_id', type: DataType.string, defaultValue: '' },
    { key: 'shares', type: DataType.number, defaultValue: 0 },
    { key: 'average_cost', type: DataType.number, defaultValue: 0 },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof PortfolioModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to PortfolioModel data
 */
function PortfolioModelFromValues(values: Value[]): PortfolioModel {
  const data: Partial<PortfolioModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'stock_id':
        data.stock_id = ParseValue(value, DataType.string) as string;
        break;
      case 'shares':
        data.shares = ParseValue(value, DataType.number) as number;
        break;
      case 'average_cost':
        data.average_cost = ParseValue(value, DataType.number) as number;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as PortfolioModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for StockIdUserId fields
 */
function createIndexStockIdUserId(
  stock_id: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, stock_id, 'stock_id'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['stock_id', 'user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default PortfolioORM;