// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: order.
// - Entity ID: 102019ac49f11007292bc8d70f146a50564.
// - Entity Version: 102019b11cfa3a378f586276c85196669dd.
// - Task ID: 693bdaebf3e1deef7a9703e2.
// - Task Root ID: 69281530eba4976d6c38ab7a.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for OrderOrderType
 */
export enum OrderOrderType {
  Unspecified = 0,
  Market = 1,
  Limit = 2,
  Stop = 3,
}
/**
 * Enumeration for OrderSide
 */
export enum OrderSide {
  Unspecified = 0,
  Buy = 1,
  Sell = 2,
}
/**
 * Enumeration for OrderStatus
 */
export enum OrderStatus {
  Unspecified = 0,
  Pending = 1,
  Executed = 2,
  Cancelled = 3,
}



/**
 * Interface for OrderModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface OrderModel {
  id: string;
  user_id: string;
  stock_id: string;
  order_type: OrderOrderType;
  side: OrderSide;
  quantity: number;
  price?: number | null;
  status: OrderStatus;
  executed_price?: number | null;
  executed_at?: string | null;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for Order entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class OrderORM {
  private static instance: OrderORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac49f11007292bc8d70f146a50564';
    this.entityName = 'order';
    this.entityVersion = '102019b11cfa3a378f586276c85196669dd';
    this.taskId = '693bdaebf3e1deef7a9703e2';
    this.taskRootId = '69281530eba4976d6c38ab7a';
  }

  /**
   * Get singleton instance of OrderORM
   */
  public static getInstance(): OrderORM {
    if (!OrderORM.instance) {
      OrderORM.instance = new OrderORM();
    }
    
    return OrderORM.instance;
  }

  /**
   * Get all Order records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllOrder(): Promise<OrderModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Order record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertOrder(data: OrderModel[]): Promise<OrderModel[]> {
    const structured = data.map((item) => CreateData(OrderModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Order records
   */
  async purgeAllOrder(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Order records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listOrder(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[OrderModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get order by Id index
   * This function gets data by index.
   */
  async getOrderById(
    id: string,
  ): Promise<OrderModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) order by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setOrderById(
    id: string,
    data: OrderModel
  ): Promise<OrderModel[]> {
    const index = createIndexId(
      id
    );

    const values = OrderModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete order by Id index
   */
  async deleteOrderById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get order by StatusUserId index
   * This function gets data by index.
   */
  async getOrderByStatusUserId(
    status: OrderStatus,
    user_id: string,
  ): Promise<OrderModel[]> {
    const index = createIndexStatusUserId(
      status,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) order by StatusUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setOrderByStatusUserId(
    status: OrderStatus,
    user_id: string,
    data: OrderModel
  ): Promise<OrderModel[]> {
    const index = createIndexStatusUserId(
      status,
      user_id
    );

    const values = OrderModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete order by StatusUserId index
   */
  async deleteOrderByStatusUserId(
    status: OrderStatus,
    user_id: string
  ): Promise<void> {
    const index = createIndexStatusUserId(
      status,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get order by StockId index
   * This function gets data by index.
   */
  async getOrderByStockId(
    stock_id: string,
  ): Promise<OrderModel[]> {
    const index = createIndexStockId(
      stock_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) order by StockId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setOrderByStockId(
    stock_id: string,
    data: OrderModel
  ): Promise<OrderModel[]> {
    const index = createIndexStockId(
      stock_id
    );

    const values = OrderModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete order by StockId index
   */
  async deleteOrderByStockId(
    stock_id: string
  ): Promise<void> {
    const index = createIndexStockId(
      stock_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get order by DataCreator index
   * This function gets data by index.
   */
  async getOrderByDataCreator(
    data_creator: string,
  ): Promise<OrderModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) order by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setOrderByDataCreator(
    data_creator: string,
    data: OrderModel
  ): Promise<OrderModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = OrderModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete order by DataCreator index
   */
  async deleteOrderByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get order by DataUpdater index
   * This function gets data by index.
   */
  async getOrderByDataUpdater(
    data_updater: string,
  ): Promise<OrderModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) order by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setOrderByDataUpdater(
    data_updater: string,
    data: OrderModel
  ): Promise<OrderModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = OrderModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete order by DataUpdater index
   */
  async deleteOrderByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to OrderModel data array
   */
  private resultToData(values: Data[]): OrderModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return OrderModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as OrderModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized OrderModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is OrderModel => item !== null);
  }
}

/**
 * Convert OrderModel data to Value array
 */
function OrderModelToValues(data: OrderModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'stock_id', type: DataType.string, defaultValue: '' },
    { key: 'order_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'side', type: DataType.enumeration, defaultValue: 0 },
    { key: 'quantity', type: DataType.number, defaultValue: 0 },
    { key: 'price', type: DataType.number, defaultValue: null },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'executed_price', type: DataType.number, defaultValue: null },
    { key: 'executed_at', type: DataType.string, defaultValue: null },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof OrderModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to OrderModel data
 */
function OrderModelFromValues(values: Value[]): OrderModel {
  const data: Partial<OrderModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'stock_id':
        data.stock_id = ParseValue(value, DataType.string) as string;
        break;
      case 'order_type':
        data.order_type = ParseValue(value, DataType.enumeration) as OrderOrderType;
        break;
      case 'side':
        data.side = ParseValue(value, DataType.enumeration) as OrderSide;
        break;
      case 'quantity':
        data.quantity = ParseValue(value, DataType.number) as number;
        break;
      case 'price':
        data.price = ParseValue(value, DataType.number) as number | null;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as OrderStatus;
        break;
      case 'executed_price':
        data.executed_price = ParseValue(value, DataType.number) as number | null;
        break;
      case 'executed_at':
        data.executed_at = ParseValue(value, DataType.string) as string | null;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as OrderModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for StatusUserId fields
 */
function createIndexStatusUserId(
  status: OrderStatus,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['status', 'user_id'],
    values
  };
}
/**
 * Create index for StockId fields
 */
function createIndexStockId(
  stock_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, stock_id, 'stock_id'),
  ];

  return {
    fields: ['stock_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default OrderORM;