// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: watchlist.
// - Entity ID: 102019ac49f110071389b9d530f87c99f81.
// - Entity Version: 102019b11cfa3a378f586276c85196669de.
// - Task ID: 693bdaebf3e1deef7a9703e2.
// - Task Root ID: 69281530eba4976d6c38ab7a.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";

/**
 * Interface for WatchlistModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface WatchlistModel {
  id: string;
  user_id: string;
  stock_id: string;
  position: number;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for Watchlist entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class WatchlistORM {
  private static instance: WatchlistORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac49f110071389b9d530f87c99f81';
    this.entityName = 'watchlist';
    this.entityVersion = '102019b11cfa3a378f586276c85196669de';
    this.taskId = '693bdaebf3e1deef7a9703e2';
    this.taskRootId = '69281530eba4976d6c38ab7a';
  }

  /**
   * Get singleton instance of WatchlistORM
   */
  public static getInstance(): WatchlistORM {
    if (!WatchlistORM.instance) {
      WatchlistORM.instance = new WatchlistORM();
    }

    return WatchlistORM.instance;
  }

  /**
   * Get all Watchlist records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllWatchlist(): Promise<WatchlistModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Watchlist record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertWatchlist(data: WatchlistModel[]): Promise<WatchlistModel[]> {
    const structured = data.map((item) => CreateData(WatchlistModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Watchlist records
   */
  async purgeAllWatchlist(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Watchlist records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listWatchlist(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[WatchlistModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }

  /**
   * Get watchlist by Id index
   * This function gets data by index.
   */
  async getWatchlistById(
    id: string,
  ): Promise<WatchlistModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) watchlist by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWatchlistById(
    id: string,
    data: WatchlistModel
  ): Promise<WatchlistModel[]> {
    const index = createIndexId(
      id
    );

    const values = WatchlistModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete watchlist by Id index
   */
  async deleteWatchlistById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get watchlist by StockIdUserId index
   * This function gets data by index.
   */
  async getWatchlistByStockIdUserId(
    stock_id: string,
    user_id: string,
  ): Promise<WatchlistModel[]> {
    const index = createIndexStockIdUserId(
      stock_id,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) watchlist by StockIdUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWatchlistByStockIdUserId(
    stock_id: string,
    user_id: string,
    data: WatchlistModel
  ): Promise<WatchlistModel[]> {
    const index = createIndexStockIdUserId(
      stock_id,
      user_id
    );

    const values = WatchlistModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete watchlist by StockIdUserId index
   */
  async deleteWatchlistByStockIdUserId(
    stock_id: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexStockIdUserId(
      stock_id,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get watchlist by DataCreator index
   * This function gets data by index.
   */
  async getWatchlistByDataCreator(
    data_creator: string,
  ): Promise<WatchlistModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) watchlist by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWatchlistByDataCreator(
    data_creator: string,
    data: WatchlistModel
  ): Promise<WatchlistModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = WatchlistModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete watchlist by DataCreator index
   */
  async deleteWatchlistByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get watchlist by DataUpdater index
   * This function gets data by index.
   */
  async getWatchlistByDataUpdater(
    data_updater: string,
  ): Promise<WatchlistModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) watchlist by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWatchlistByDataUpdater(
    data_updater: string,
    data: WatchlistModel
  ): Promise<WatchlistModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = WatchlistModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete watchlist by DataUpdater index
   */
  async deleteWatchlistByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to WatchlistModel data array
   */
  private resultToData(values: Data[]): WatchlistModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return WatchlistModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as WatchlistModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized WatchlistModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is WatchlistModel => item !== null);
  }
}

/**
 * Convert WatchlistModel data to Value array
 */
function WatchlistModelToValues(data: WatchlistModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'stock_id', type: DataType.string, defaultValue: '' },
    { key: 'position', type: DataType.number, defaultValue: 0 },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof WatchlistModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to WatchlistModel data
 */
function WatchlistModelFromValues(values: Value[]): WatchlistModel {
  const data: Partial<WatchlistModel> = {};

  for (const value of values) {
    if (!value.name) continue;

    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'stock_id':
        data.stock_id = ParseValue(value, DataType.string) as string;
        break;
      case 'position':
        data.position = ParseValue(value, DataType.number) as number;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }

  return data as WatchlistModel;
}

/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}

/**
 * Create index for StockIdUserId fields
 */
function createIndexStockIdUserId(
  stock_id: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, stock_id, 'stock_id'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['stock_id', 'user_id'],
    values
  };
}

/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}

/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default WatchlistORM;
