// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: price_history.
// - Entity ID: 102019ac49f110078a588cb8f7d2d817c3e.
// - Entity Version: 102019b11cfa3a378f586276c85196669dd.
// - Task ID: 693bdaebf3e1deef7a9703e2.
// - Task Root ID: 69281530eba4976d6c38ab7a.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for PriceHistoryModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface PriceHistoryModel {
  id: string;
  stock_id: string;
  price: number;
  volume: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for PriceHistory entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class PriceHistoryORM {
  private static instance: PriceHistoryORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac49f110078a588cb8f7d2d817c3e';
    this.entityName = 'price_history';
    this.entityVersion = '102019b11cfa3a378f586276c85196669dd';
    this.taskId = '693bdaebf3e1deef7a9703e2';
    this.taskRootId = '69281530eba4976d6c38ab7a';
  }

  /**
   * Get singleton instance of PriceHistoryORM
   */
  public static getInstance(): PriceHistoryORM {
    if (!PriceHistoryORM.instance) {
      PriceHistoryORM.instance = new PriceHistoryORM();
    }
    
    return PriceHistoryORM.instance;
  }

  /**
   * Get all PriceHistory records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllPriceHistory(): Promise<PriceHistoryModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new PriceHistory record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertPriceHistory(data: PriceHistoryModel[]): Promise<PriceHistoryModel[]> {
    const structured = data.map((item) => CreateData(PriceHistoryModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all PriceHistory records
   */
  async purgeAllPriceHistory(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List PriceHistory records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listPriceHistory(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[PriceHistoryModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get price_history by Id index
   * This function gets data by index.
   */
  async getPriceHistoryById(
    id: string,
  ): Promise<PriceHistoryModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) price_history by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPriceHistoryById(
    id: string,
    data: PriceHistoryModel
  ): Promise<PriceHistoryModel[]> {
    const index = createIndexId(
      id
    );

    const values = PriceHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete price_history by Id index
   */
  async deletePriceHistoryById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get price_history by CreateTimeStockId index
   * This function gets data by index.
   */
  async getPriceHistoryByCreateTimeStockId(
    create_time: string,
    stock_id: string,
  ): Promise<PriceHistoryModel[]> {
    const index = createIndexCreateTimeStockId(
      create_time,
      stock_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) price_history by CreateTimeStockId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPriceHistoryByCreateTimeStockId(
    create_time: string,
    stock_id: string,
    data: PriceHistoryModel
  ): Promise<PriceHistoryModel[]> {
    const index = createIndexCreateTimeStockId(
      create_time,
      stock_id
    );

    const values = PriceHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete price_history by CreateTimeStockId index
   */
  async deletePriceHistoryByCreateTimeStockId(
    create_time: string,
    stock_id: string
  ): Promise<void> {
    const index = createIndexCreateTimeStockId(
      create_time,
      stock_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get price_history by DataCreator index
   * This function gets data by index.
   */
  async getPriceHistoryByDataCreator(
    data_creator: string,
  ): Promise<PriceHistoryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) price_history by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPriceHistoryByDataCreator(
    data_creator: string,
    data: PriceHistoryModel
  ): Promise<PriceHistoryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = PriceHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete price_history by DataCreator index
   */
  async deletePriceHistoryByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get price_history by DataUpdater index
   * This function gets data by index.
   */
  async getPriceHistoryByDataUpdater(
    data_updater: string,
  ): Promise<PriceHistoryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) price_history by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPriceHistoryByDataUpdater(
    data_updater: string,
    data: PriceHistoryModel
  ): Promise<PriceHistoryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = PriceHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete price_history by DataUpdater index
   */
  async deletePriceHistoryByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to PriceHistoryModel data array
   */
  private resultToData(values: Data[]): PriceHistoryModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return PriceHistoryModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as PriceHistoryModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized PriceHistoryModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is PriceHistoryModel => item !== null);
  }
}

/**
 * Convert PriceHistoryModel data to Value array
 */
function PriceHistoryModelToValues(data: PriceHistoryModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'stock_id', type: DataType.string, defaultValue: '' },
    { key: 'price', type: DataType.number, defaultValue: 0 },
    { key: 'volume', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof PriceHistoryModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to PriceHistoryModel data
 */
function PriceHistoryModelFromValues(values: Value[]): PriceHistoryModel {
  const data: Partial<PriceHistoryModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'stock_id':
        data.stock_id = ParseValue(value, DataType.string) as string;
        break;
      case 'price':
        data.price = ParseValue(value, DataType.number) as number;
        break;
      case 'volume':
        data.volume = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as PriceHistoryModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for CreateTimeStockId fields
 */
function createIndexCreateTimeStockId(
  create_time: string,
  stock_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
    CreateValue(DataType.string, stock_id, 'stock_id'),
  ];

  return {
    fields: ['create_time', 'stock_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default PriceHistoryORM;