// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: educational_content.
// - Entity ID: 102019ac49f11007d7c89337179bd1adf1d.
// - Entity Version: 102019b11cfa3a378f586276c85196669dd.
// - Task ID: 693bdaebf3e1deef7a9703e2.
// - Task Root ID: 69281530eba4976d6c38ab7a.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for EducationalContentCategory
 */
export enum EducationalContentCategory {
  Unspecified = 0,
  Basics = 1,
  Fundamentals = 2,
  HYBE = 3,
  KPOP = 4,
  Strategies = 5,
}
/**
 * Enumeration for EducationalContentContentType
 */
export enum EducationalContentContentType {
  Unspecified = 0,
  Article = 1,
  Video = 2,
}
/**
 * Enumeration for EducationalContentDifficulty
 */
export enum EducationalContentDifficulty {
  Unspecified = 0,
  Beginner = 1,
  Intermediate = 2,
  Advanced = 3,
}



/**
 * Interface for EducationalContentModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface EducationalContentModel {
  id: string;
  title: string;
  description?: string | null;
  content_type: EducationalContentContentType;
  content_url: string;
  category: EducationalContentCategory;
  difficulty: EducationalContentDifficulty;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for EducationalContent entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class EducationalContentORM {
  private static instance: EducationalContentORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac49f11007d7c89337179bd1adf1d';
    this.entityName = 'educational_content';
    this.entityVersion = '102019b11cfa3a378f586276c85196669dd';
    this.taskId = '693bdaebf3e1deef7a9703e2';
    this.taskRootId = '69281530eba4976d6c38ab7a';
  }

  /**
   * Get singleton instance of EducationalContentORM
   */
  public static getInstance(): EducationalContentORM {
    if (!EducationalContentORM.instance) {
      EducationalContentORM.instance = new EducationalContentORM();
    }
    
    return EducationalContentORM.instance;
  }

  /**
   * Get all EducationalContent records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllEducationalContent(): Promise<EducationalContentModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new EducationalContent record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertEducationalContent(data: EducationalContentModel[]): Promise<EducationalContentModel[]> {
    const structured = data.map((item) => CreateData(EducationalContentModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all EducationalContent records
   */
  async purgeAllEducationalContent(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List EducationalContent records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listEducationalContent(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[EducationalContentModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get educational_content by Id index
   * This function gets data by index.
   */
  async getEducationalContentById(
    id: string,
  ): Promise<EducationalContentModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) educational_content by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setEducationalContentById(
    id: string,
    data: EducationalContentModel
  ): Promise<EducationalContentModel[]> {
    const index = createIndexId(
      id
    );

    const values = EducationalContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete educational_content by Id index
   */
  async deleteEducationalContentById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get educational_content by CategoryDifficulty index
   * This function gets data by index.
   */
  async getEducationalContentByCategoryDifficulty(
    category: EducationalContentCategory,
    difficulty: EducationalContentDifficulty,
  ): Promise<EducationalContentModel[]> {
    const index = createIndexCategoryDifficulty(
      category,
      difficulty
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) educational_content by CategoryDifficulty index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setEducationalContentByCategoryDifficulty(
    category: EducationalContentCategory,
    difficulty: EducationalContentDifficulty,
    data: EducationalContentModel
  ): Promise<EducationalContentModel[]> {
    const index = createIndexCategoryDifficulty(
      category,
      difficulty
    );

    const values = EducationalContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete educational_content by CategoryDifficulty index
   */
  async deleteEducationalContentByCategoryDifficulty(
    category: EducationalContentCategory,
    difficulty: EducationalContentDifficulty
  ): Promise<void> {
    const index = createIndexCategoryDifficulty(
      category,
      difficulty
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get educational_content by DataCreator index
   * This function gets data by index.
   */
  async getEducationalContentByDataCreator(
    data_creator: string,
  ): Promise<EducationalContentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) educational_content by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setEducationalContentByDataCreator(
    data_creator: string,
    data: EducationalContentModel
  ): Promise<EducationalContentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = EducationalContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete educational_content by DataCreator index
   */
  async deleteEducationalContentByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get educational_content by DataUpdater index
   * This function gets data by index.
   */
  async getEducationalContentByDataUpdater(
    data_updater: string,
  ): Promise<EducationalContentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) educational_content by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setEducationalContentByDataUpdater(
    data_updater: string,
    data: EducationalContentModel
  ): Promise<EducationalContentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = EducationalContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete educational_content by DataUpdater index
   */
  async deleteEducationalContentByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to EducationalContentModel data array
   */
  private resultToData(values: Data[]): EducationalContentModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return EducationalContentModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as EducationalContentModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized EducationalContentModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is EducationalContentModel => item !== null);
  }
}

/**
 * Convert EducationalContentModel data to Value array
 */
function EducationalContentModelToValues(data: EducationalContentModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'content_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'content_url', type: DataType.string, defaultValue: '' },
    { key: 'category', type: DataType.enumeration, defaultValue: 0 },
    { key: 'difficulty', type: DataType.enumeration, defaultValue: 0 },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof EducationalContentModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to EducationalContentModel data
 */
function EducationalContentModelFromValues(values: Value[]): EducationalContentModel {
  const data: Partial<EducationalContentModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'content_type':
        data.content_type = ParseValue(value, DataType.enumeration) as EducationalContentContentType;
        break;
      case 'content_url':
        data.content_url = ParseValue(value, DataType.string) as string;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.enumeration) as EducationalContentCategory;
        break;
      case 'difficulty':
        data.difficulty = ParseValue(value, DataType.enumeration) as EducationalContentDifficulty;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as EducationalContentModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for CategoryDifficulty fields
 */
function createIndexCategoryDifficulty(
  category: EducationalContentCategory,
  difficulty: EducationalContentDifficulty
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, category, 'category'),
    CreateValue(DataType.enumeration, difficulty, 'difficulty'),
  ];

  return {
    fields: ['category', 'difficulty'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default EducationalContentORM;